
name: "build and push to docker hub"

on:
  create:
    tags:
      - "v*"
  # release:
  #   types:
  #     - created
  schedule:
    - cron:  '0 0 15 3,6,9,12 *' # POSIX cron syntax (UTC times)

jobs:
  push_parent:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }} # only run with tag
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code at current commit"
        uses: actions/checkout@v2
      - name: Prepare tags
        if: ${{ (github.event_name == 'release' && github.event.action == 'created') || github.event_name == 'create' }} # || github.event.pull_request.head.repo.full_name == github.repository
        id: prepare
        run: |
          # TAGS=${{ github.repository }}:sha-${GITHUB_SHA:0:7}
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.pull_request.number }}-merge
          fi
          if [[ -n $VERSION ]]; then
            TAGS="$TAGS,${{ github.repository }}:${VERSION}"
          fi
          if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS,${{ github.repository }}:latest"
          fi
          echo ::set-output name=tags::${TAGS}
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to docker hub
        if: ${{ (github.event_name == 'release' && github.event.action == 'created') || github.event_name == 'create' }} # || github.event.pull_request.head.repo.full_name == github.repository
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Build and push image to docker hub"
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: base/.
          push: ${{ (github.event_name == 'release' && github.event.action == 'created') || github.event_name == 'create' }} # || github.event.pull_request.head.repo.full_name == github.repository }}
          tags: ${{ steps.prepare.outputs.tags }}

  push_children:
    needs: push_parent
    runs-on: ubuntu-latest
    strategy:
      matrix:
        children:
          - 'terraform'
          - 'selenium-chrome'
    steps:
      - name: "Checkout source code at current commit"
        uses: actions/checkout@v2
      - name: Prepare tags
        if: ${{ (github.event_name == 'release' && github.event.action == 'created') || github.event_name == 'create' }} # || github.event.pull_request.head.repo.full_name == github.repository
        id: prepare
        run: |
          # TAGS="${{ github.repository }}-${{ matrix.children }}:sha-${GITHUB_SHA:0:7}"
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.pull_request.number }}-merge
          fi
          if [[ -n $VERSION ]]; then
            TAGS="$TAGS,${{ github.repository }}-${{ matrix.children }}:${VERSION}"
          fi
          if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS,${{ github.repository }}-${{ matrix.children }}:latest"
          fi
          echo ::set-output name=tags::${TAGS}
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to docker hub
        if: ${{ (github.event_name == 'release' && github.event.action == 'created') || github.event_name == 'create' }} # || github.event.pull_request.head.repo.full_name == github.repository
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Build and push image to docker hub"
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.children }}/.
          push: ${{ (github.event_name == 'release' && github.event.action == 'created') || github.event_name == 'create' }} # || github.event.pull_request.head.repo.full_name == github.repository }}
          tags: ${{ steps.prepare.outputs.tags }}
